title: Hello, world! I'm Samay Mahajan
description: > # this means to ignore newlines until "baseurl:"
  Engineering is in my genetic memory. I am a quick learner and solution oriented person, love to explore how things works, DIY stuff, fix broken things, sometime doing frugal innovation(jugaad). I am both technology and photography enthusiastic.
Having overall 10+ years of experience with good organisations like Sapient, Royal Bank of Scotland, Birlasoft. I started my career with .Net development, but my technology enthusiasm helps me to explore new areas to learn and I finally adapted to DevOps Culture. Now, I am full time DevOps Engineer. 
Having expertise in Continuos Integration, Continuos Deployment, containerisation, Google Cloud, Powershell Scripting and Automation Solutions. Also having good experience with full stack web development, using NodeJS, ReactJS, Express and MongoDB.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://samaymahajan.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: samaymahajan

# Author Settings
author: Samay Mahajan
author-img: samay.jpg # add your photo
about-author: DevOps Engineer & Full stack web developer. A quick learner and solution oriented person. Technology and Photography enthusiastic.
social-twitter: samaymahajan
social-facebook: samaymahajan
social-github: samaymahajan
social-linkedin: samaymahajan
social-email: samaymahajan@gmail.com

# Disqus
discus-identifier: samaymahajan

# Tracker
analytics: UA-190559-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
